node {
    sh("cp /home/Dockerfile .")
    stage('Preparation') {
        dir('Data-Layer') {
            git branch: 'develop',
            url: 'https://github.com/AMDVAT/Data-Layer.git'
        }
        dir('Web-Server') {
            git branch: 'develop',
            url: 'https://github.com/AMDVAT/Web-Server.git'
        }
    }                                     
    stage('docker build/push') {            
     docker.withRegistry('https://index.docker.io/v1/', '7fdd6dbb-2e62-4cc1-b161-86e42eaaf93a') {
       def app = docker.build("charliecech/docker-jenkins-example", '.').push()
     }                                     
   } 
}
